apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-gateway
  namespace: logging
spec:
  ingressClassName: cilium
  rules:
  - host: loki-gateway.localhost
    http:
      paths:
      - backend:
          service:
            name: loki-gateway
            port:
              name: http-metrics
        path: /
        pathType: Prefix
