kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 20080
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 30443
    hostPort: 20443
    listenAddress: 127.0.0.1
    protocol: TCP
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
