apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-redmine
  namespace: redmine
spec:
  instances: 1

  bootstrap:
    initdb:
      database: redmine_production
      owner: redmine

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
