apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: redmine-app
  template:
    metadata:
      labels:
        app: redmine-app
    spec:
      containers:
      - image: redmine:6.0.4
        name: redmine
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: REDMINE_DB_POSTGRES
          valueFrom:
            secretKeyRef:
              name: redmine-db-app
              key: host
        - name: REDMINE_DB_PORT
          valueFrom:
            secretKeyRef:
              name: redmine-db-app
              key: port
        - name: REDMINE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: redmine-db-app
              key: user
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redmine-db-app
              key: password
        - name: REDMINE_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: redmine-db-app
              key: dbname
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: secret_key_base
        volumeMounts:
        - name: redmine-persistent-storage
          mountPath: /usr/src/redmine/files
      volumes:
      - name: redmine-persistent-storage
        persistentVolumeClaim:
          claimName: redmine-pvc
