configs:
  cm:
    resource.exclusions: |
      # https://docs.cilium.io/en/latest/configuration/argocd-issues/
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
    # https://stackoverflow.com/questions/75488142/troubleshooting-ingress-stuck-in-progressing-state-in-argocd
    # https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-application-stuck-in-progressing-state
    resource.customizations: |
      networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            if obj.status ~= nil then
              hs.status = "Healthy"
            end
            return hs
  params:
    server.insecure: true

## Application controller
controller:
  ## Application controller metrics configuration
  metrics:
    # -- Deploy metrics service
    enabled: true
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: enable
      # -- PrometheusRule namespace
      namespace: "monitoring" # "monitoring"

## Server
server:
  ## Server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: true
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: true
      # -- Prometheus ServiceMonitor namespace
      namespace: "monitoring"  # monitoring

## Repo Server
repoServer:
  ## Repo server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: true
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: true
      # -- Prometheus ServiceMonitor namespace
      namespace: "monitoring" # "monitoring"
