name: Build and Push Docker Image

on:
  push:
    paths:
      - 'reveal-env/Dockerfile'
      - 'reveal-env/Gemfile*'
      - 'reveal-env/config.ru'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    strategy:
      matrix:
        platform: [amd64, arm64]
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-22.04-arm64' || 'ubuntu-latest' }}

    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build \
            --platform linux/${{ matrix.platform }} \
            --tag ghcr.io/${{ github.repository_owner }}/reveal-env:${{ matrix.platform }} \
            ./reveal-env
          docker push ghcr.io/${{ github.repository_owner }}/reveal-env:${{ matrix.platform }}
