name: Build and Push Docker Image

on:
  push:
    paths:
      - 'reveal-env/Dockerfile'
      - 'reveal-env/Gemfile*'
      - 'reveal-env/config.ru'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/reveal-env:latest ./reveal-env

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/reveal-env:latest
