name: Build and Push Docker Image

on:
  push:
    paths:
      - 'reveal-env/Dockerfile'
      - 'reveal-env/Gemfile*'
      - 'reveal-env/config.ru'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-architecture Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository_owner }}/reveal-env:latest \
            --push \
            ./reveal-env
